FROM rustlang/rust:nightly-alpine AS builder
RUN apk add --no-cache musl-dev gcc
WORKDIR /app
COPY . .
RUN cargo build --release --target x86_64-unknown-linux-musl --workspace

FROM alpine:latest
COPY --from=builder /app/target/x86_64-unknown-linux-musl/release/lush /usr/local/bin/lush
COPY --from=builder /app/target/x86_64-unknown-linux-musl/release/lush-lsp /usr/local/bin/lush-lsp
ENTRYPOINT ["/usr/local/bin/lush"]
