FROM rust:1.80-alpine AS builder
RUN apk add --no-cache musl-dev gcc
WORKDIR /app
COPY . .
RUN cargo build --release --target x86_64-unknown-linux-musl

FROM alpine:latest
COPY --from=builder /app/target/x86_64-unknown-linux-musl/release/lush /usr/local/bin/lush
ENTRYPOINT ["/usr/local/bin/lush"]
